### ISSUE TITLE
БД Здания

### ISSUE THREAD

**Issue by WhyWeLive** [RunningGun4/VseSuda#5]
Создать базу данных общественных зданий:

- 5 случайных городов (папки)
    - 5 случайных районов (папки)
        - папка долгострой
            - 50 случайных зданий (файлы) + заполненные случайным значением
        - папка достопримечательности
            - 50 случайных зданий (файлы) + заполненные случайным значением
        - папка новые здания
            - 50 случайных зданий (файлы) + заполненные случайным значением

**Comment by pomerlok** [comment]
сори скуфанулся
